### ISSUE TITLE
Refactor: remove all usages of EventBus in favour of Vuex

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#1006] opened 2021-01-28 15:43 UTC
@mradkov I don't like all this PR at all but I have no idea how to easily achieve the SSR (remove import store explicitly) 
This should work as a temporary solution. It also redirects to the feed page with the last commit https://github.com/aeternity/superhero-ui/pull/1003/commits/6e1db153b3e122c5234b1af198d47040edfa4687

_Originally posted by @shapkarin in https://github.com/aeternity/superhero-ui/pull/1003#discussion_r566124696_

**Comment by davidyuk** [comment] 2021-07-08 11:08
duplicate of #660

**Closed by davidyuk** 2021-07-08 11:08 UTC
Labels: area/refactoring, priority/high
