### ISSUE TITLE
The images flash after the first hover after site reload

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#559] opened 2020-05-28 07:23 UTC

**Comment by CedrikNikita** [comment] 2020-05-31 09:03
This is not the case for me in both ff and chrome.

**Comment by stanislav-slavov** [comment] 2020-06-04 09:12
I can't reproduce the issue anymore. I think it is fixed with the introduction of inline svg-s #589

**Closed** 2020-06-04 11:51 UTC
Labels: kind/bug
