### ISSUE TITLE
Cannot create a poll

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-ui#921] opened 2020-12-14 04:29 UTC
There's no button to Create a New Poll?

![Screen Shot 2020-12-14 at 12 27 59 PM](https://user-images.githubusercontent.com/31926001/102040518-fde0e680-3e07-11eb-9a43-f1820ecdc548.png)

**Comment by davidyuk** [comment] 2020-12-14 09:56
As I know there should be a separate confirmation of connection wallet to the Voting app, did you accept that?
@Liubov-crypto can you reproduce this?

**Comment by mradkov** [comment] 2020-12-14 09:57
If your wallet is connected you will be able to see it.

<img width="675" alt="Screenshot 2020-12-14 at 11 56 51" src="https://user-images.githubusercontent.com/13139371/102067201-75f8dd80-3e03-11eb-997c-e10ac1d7d84f.png">

**Comment by Liubov-crypto** [comment] 2020-12-14 10:11
> As I know there should be a separate confirmation of connection wallet to the Voting app, did you accept that?
> @Liubov-crypto can you reproduce this?

This issue is only reproduced when the wallet is not connected to the superhero UI.
I agree with Milen when the wallet is connected to the superhero UI and with governance, everything works correctly.

**Comment by thescientress** [comment] 2020-12-14 10:26
Nope. My wallet is connected to the UI. Still no button.

![Screen Shot 2020-12-14 at 6 25 19 PM](https://user-images.githubusercontent.com/31926001/102070256-d440b300-3e39-11eb-9f19-9a85f13c93b8.png)

**Comment by Liubov-crypto** [comment] 2020-12-14 10:42
> Nope. My wallet is connected to the UI. Still no button.
> 
> ![Screen Shot 2020-12-14 at 6 25 19 PM](https://user-images.githubusercontent.com/31926001/102070256-d440b300-3e39-11eb-9f19-9a85f13c93b8.png)

You should also connect to governance.aepp (second pop-up). After connecting it should work

![22](https://user-images.githubusercontent.com/69896204/102071781-a2175d00-3e09-11eb-9fda-e0d5963cd786.png)

**Comment by thescientress** [comment] 2020-12-14 10:56
Never got a second pop-up, just one which I confirmed. Is there a way for me to add that permission to connect?

**Comment by Liubov-crypto** [comment] 2020-12-14 11:19
> Never got a second pop-up, just one which I confirmed. Is there a way for me to add that permission to connect?

I get them automatically. Try clearing the cache and reconnecting to the superhero.

**Comment by davidyuk** [comment] 2020-12-14 11:32
> Nope. My wallet is connected to the UI. Still no button.

It may be not obvious, but it doesn't meen that it is connected. Because UI also remembers the last commencted account for the deeplink use case.

**Comment by mradkov** [comment] 2021-03-12 11:30
I'm closing this issue. If it is still reproducible in the future will reopen.

**Closed by mradkov** 2021-03-12 11:30 UTC
